### ISSUE TITLE
Potential issue with third-body efficiencies

### ISSUE THREAD

**Issue by deep6kb** [kyleniemeyer/irrev_mech#2]
When trying to run irrev_mech (having run it successfully previously), I am getting the following error:

Traceback (most recent call last):
  File "irrev_mech.py", line 433, in <module>
    convert_mech_irrev(args.mech, args.thermo, args.range)
  File "irrev_mech.py", line 310, in convert_mech_irrev
    [elems, specs, reacs, units] = mech.read_mech(mech_name)
  File ".../reduction/Naik_C12/irrev_mech/mech_interpret.py", line 477, in read_mech
    pair = [line_split[i], float(line_split[i + 1])]
IndexError: list index out of range

This section is apparently related to the read-in for three-body reaction efficiencies. Any help would be appreciated.

**Comment by kyleniemeyer** [comment]
pretty sure the primary issue is that the mech_interpret.py used in irrev_mech did not support CHEB or PLOG reactions! should be fixed shortly.

**Comment by deep6kb** [comment]
Was just about to post on that issue.  When I remove the PLOG lines (didn't realize they were in there, there are only 4 out of the ~700 reactions) the code works fine.

On another note, I have tried running the code for GRI 3.0, and while it runs without shooting an error, it appears to get stuck in a loop and never completes.  When killed, the traceback indicates that it is stuck while reading the thermo file.
Traceback (most recent call last):
  File "irrev_mech.py", line 433, in <module>
    convert_mech_irrev(args.mech, args.thermo, args.range)
  File "irrev_mech.py", line 315, in convert_mech_irrev
    mech.read_thermo(file, elems, specs)
  File ".../reduction/Naik_C12/irrev_mech/mech_interpret.py", line 507, in read_thermo
    """

**Comment by kyleniemeyer** [comment]
OK—mechanisms with PLOG should work now. CHEB is still not supported since I need to figure out how that would even work...
