### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by yuj056** [kyleniemeyer/irrev_mech#6]
Dear developer, 

I have the following problem when running your code irrev_mech. The detailed error info is listed below.

Traceback (most recent call last):
  File "/Users/yuanjie/anaconda/bin/irrev_mech", line 11, in <module>
    load_entry_point('irrev-mech==2.1.0', 'console_scripts', 'irrev_mech')()
  File "/Users/yuanjie/anaconda/lib/python2.7/site-packages/irrev_mech-2.1.0-py2.7.egg/irrev_mech/__main__.py", line 50, in main
    convert_mech_irrev(args.chem, args.thermo, args.range, args.output, args.numprocs)
  File "/Users/yuanjie/anaconda/lib/python2.7/site-packages/irrev_mech-2.1.0-py2.7.egg/irrev_mech/irrev_mech.py", line 458, in convert_mech_irrev
    with Pool(processes=n_procs) as pool:
AttributeError: __exit__

Could you pls help me look into this?

Also, I installed Cantera in my laptop, is that the reason these two are incompatible?

Thanks
jyj

**Comment by kyleniemeyer** [comment]
hello @yuj056, I just tried running this again on my machine (which is using Python 3.6) and it completed with no problems. Are you limited to using Python 2.7, or could you upgrade to 3.5 or 3.6?

Also, this program does not interact with Cantera, so there shouldn't be any conflict.

**Comment by yuj056** [comment]
Hi Kyle,

Yes, after I update python it works.

Thanks,

Yuanjie

**Comment by kyleniemeyer** [comment]
OK great. I will remove the claim of Python 2.x compatibility for the code, as that seems to be the cause.
